name: TweakcraftUtils
main: com.guntherdw.bukkit.tweakcraft.TweakcraftUtils
version: 1.4.0-IRCPlugin
commands:
  tc:
    description: General tweakcraftutils command
    usage: /<command> ...
  admin:
    description: Send message to admins
    usage: /<command> <message>
    aliases: a
  admin-add:
    description: Adds a player to the admin-msg list
    usage: /<command> <player>
  admin-remove:
    description: Removes a player from the admin-msg list
    usage: /<command> <player>
  admin-list:
    description: Show the current admin-msg list
    usage: /<command>
  admon:
    description: Automatically sends any msg as an admin message
    usage: /<command>
  admoff:
    description: Makes you chat like normal again
    usage: /<command>
  who:
    description: Shows the list of currently connected players
    usage: /<command>
    aliases: playerlist
  tp:
    description: Teleports you to another player
    usage: /<command> <player>
  tpoff:
    description: Turns off teleporting for you!
    usage: /<command>
  tpon:
    description: Turns tp'ing back on
    usage: /<command>
  tplist:
    description: Shows who has /tpoff
    usage: /<command>
  ignite:
    description: Put someone on fire
    usage: /<command> <player>
  ext:
    description: Extinguish yourself or someone else
    usage: /<command> <player>
  lc:
    description: Toggle local chat
    usage: /<command>
  tele:
    description: Teleport to a specific location
    usage: /<command> ...
  tphere:
    description: Teleport a player to you
    usage: /<command> <player>
    aliases: s
  seen:
    description: Report the last logout time of the player
    usage: /<command> <player>
  broadcast:
    description: Broadcasts said message to the server
    usage: /<command> <message>
    aliases: b
  tpmob:
    description: Teleports you to a mob
    usage: /<command> <mobid>
  kick:
    description: Kicks a player with reason
    usage: /<command> <player> [reason]
  ban:
    description: Bans a player with a reason
    usage: /<command> <player> [reason]
  beun:
    description: Beunhaas a player for a time period
    usage: /<command> <player> <time> [reason]
  unban:
    description: Unban a player
    usage: /<command> <player>
  mute:
    description: Mute a player
    usage: /<command> <player>
  item:
    description: Give yourself an item of choise
    usage: /<command> <itemID/itemName> [amount] [player]
    aliases: [i, give]
  world:
    description: Teleports you to a world of choice
    usage: /<command> <world>
  getpos:
    description: Shows your current position
    usage: /<command> [player]
  compass:
    description: Shows your current orientation
    usage: /<command>
  spawnmob:
    description: Spawns mobs at your position
    usage: /<command> <mobname> [amount] [player]
  motd:
    description: Show the message of the day!
    usage: /<command>
  spawn:
    description: Sends you to the spawn of the world you're in
    usage: /<command>
  setspawn:
    description: Sets the spawn of the current world
    usage: /<command>
  time:
    description: Sets the time in this world
    usage: /<command> <time>
  me:
    description: Broadcasts a message in third person
    usage: /<command> <message>
  plugin:
    description: General plugin command
    usage: /<command> <list|load|enable|disable|reload> <plugin>
  msg:
    description: Send a message to a player
    usage: /<command> <player> <message>
  reply:
    description: Reply to the last player that sent a message to you
    usage: /<command> <message>
    aliases: [r, re]
  banlist:
    description: Lists the current bans
    usage: /<command>
  listworlds:
    description: Lists the currently active worlds
    usage: /<command>
    aliases: lw