name: TweakcraftUtils
main: com.guntherdw.bukkit.tweakcraft.TweakcraftUtils
# softdepend: [ 'CraftIRC' ]
# depend: [ CraftIRC ]
version: 2.8.1-git
authors:
  - GuntherDW
  - Meaglin
  - sk89q
  - Edoxile
website: https://github.com/GuntherDW/TweakcraftUtils
description: A general usage plugin primarily aimed at Tweakcraft, but can be used by any server
database: true
commands:
  tweakcraft:
    description: General tweakcraftutils command
    usage: /<command> ...
    aliases: [ 'tc' ]
  admin:
    description: Send message to admins
    usage: /<command> <message>
    aliases: [ 'a' ]
  admin-add:
    description: Adds a player to the admin-msg list
    usage: /<command> <player>
  admin-remove:
    description: Removes a player from the admin-msg list
    usage: /<command> <player>
  admin-list:
    description: Show the current admin-msg list
    usage: /<command>
  admon:
    description: Automatically sends any msg as an admin message
    usage: /<command>
  admoff:
    description: Makes you chat like normal again
    usage: /<command>
  who:
    description: List of currently connected players
    usage: /<command>
    aliases: [ 'playerlist' ]
  lwho:
    description: List of currently connected players in-range (localchat)
    usage: /<command>
    aliases: [ 'localwho' ]
  tp:
    description: Teleports you to another player
    usage: /<command> <player>
  tpoff:
    description: Turns off teleporting for you!
    usage: /<command>
  tpon:
    description: Turns tp'ing back on
    usage: /<command>
  tplist:
    description: Shows who has /tpoff
    usage: /<command>
  ignite:
    description: Put someone on fire
    usage: /<command> <player>
  ext:
    description: Extinguish yourself or someone else
    usage: /<command> <player>
    aliases: [ 'extself' ]
  lc:
    description: Toggle local chat
    usage: /<command>
  rc:
    description: Toggle region chat
    usage: /<command>
  wc:
    description: Toggle WorldChat
    usage: /<command>
  zc:
    description: Toggle ZoneChat
    usage: /<command>
  chatmode:
    description: ChatMode control
    usage: /<command> <chatmode>
    aliases: [ 'cm' ]
  tele:
    description: Teleport to a specific location
    usage: /<command> ...
  tphere:
    description: Teleport a player to you
    usage: /<command> <player>
    aliases: [ 's', 'summon' ]
  seen:
    description: Report the last logout time of the player
    usage: /<command> <player>
  broadcast:
    description: Broadcasts said message to the server
    usage: /<command> <message>
    aliases: [ 'b', 'broa' ]
  tpmob:
    description: Teleports a mob to you
    usage: /<command> <mobid>
  kick:
    description: Kicks a player with reason
    usage: /<command> <player> [reason]
  ban:
    description: Bans a player with a reason
    usage: /<command> <player> [reason]
  beun:
    description: Beunhaas a player for a time period
    usage: /<command> <player> <time> [reason]
  unban:
    description: Unban a player
    usage: /<command> <player>
  mute:
    description: Mute a player
    usage: /<command> <player>
  item:
    description: Give yourself an item of choice
    usage: /<command> <itemID/itemName> [amount] [player]
    aliases: [ 'i', 'give' ]
  world:
    description: Teleports you to a world of choice
    usage: /<command> <world>
  getpos:
    description: Shows your current position
    usage: /<command> [player]
  compass:
    description: Shows your current orientation
    usage: /<command>
  spawnmob:
    description: Spawns mobs at your crosshair
    usage: /<command> <mobname> [amount] [player]
  motd:
    description: Show the message of the day!
    usage: /<command>
  spawn:
    description: Sends you to the spawn of the world you're in
    usage: /<command>
  getspawn:
    description: Gets the spawn location for the world
    usage: /<command>
  setspawn:
    description: Sets the spawn of the current world
    usage: /<command>
  time:
    description: Sets the time in this world
    usage: /<command> <time>
  me:
    description: Broadcasts a message in third person
    usage: /<command> <message>
  plugin:
    description: General plugin command
    usage: /<command> <list|load|enable|disable|reload> <plugin>
  msg:
    description: Send a message to a player
    usage: /<command> <player> <message>
    aliases: [ 'tell', 'whisper' ]
  reply:
    description: Reply to the last msg
    usage: /<command> <message>
    aliases: [ 'r', 're' ]
  banlist:
    description: Lists the current bans
    usage: /<command>
  listworlds:
    description: Lists the currently active worlds
    usage: /<command>
    aliases: [ 'lw' ]
  clearinventory:
    description: Clear a player's inventory
    usage: /<command> [player]
    aliases: [ 'cli' ]
  strike:
    description: Strike lightning at command
    usage: /<command> [player]
    aliases: [ 'ls' ]
  strikebind:
    description: Bind the lightning tool to a tool/item
    usage: /<command>
    aliases: [ 'lsbind' ]
  rain:
    description: Turn storm on or off at command
    usage: /<command> <world> <on|off>
    aliases: [ 'storm' ]
  thunder:
    description: Turn thunder on or off at command
    usage: /<command> <world> <on|off>
  helptcutils:
    description: What you're reading right now
    usage: /<command>
  tpback:
    description: Go back to where you once came from!
    usage: /<command>
    aliases: [ 'tpb', 'back' ]
  tpforward:
    description: Go back to where you once backed from!
    usage: /<command>
    aliases: [ 'tpf', 'forward' ]
  debug:
    description: Various debug commands
    usage: /<command> <test>
  tamer:
    description: Tamer tool control
    usage: /<command> <mode>
  nick:
    description: Give someone a nick
    usage: /<command> <nick>
  whois:
    description: Find out who's behind that nick!
    usage: /<command> <nick>
#  groupchat:
#    description: GroupChat control
#    usage: /<command>
#    aliases: [ 'gc' ]
  gc:
    description: Remove ChatMode subscription
    usage: /<command>
  eject:
    description: Eject your freeloader!
    usage: /<command>
  donotmount:
    description: Toggle mounting access
    usage: /<command>
    aliases: [ 'dnm', 'nomount' ]
  viewdistance:
    desciption: ViewDistance control!
    usage: /<command> [p:<player>] [distance]
  afk:
    description: Manually toggle your AFK status
    usage: /<command>
  tntarrow:
    description: Toggles the use of TNT Arrows.
    usage: /<command>
    aliases: [ 'tnta' ]
  addexp:
    description: Adds experience to you or someone else
    usage: /<command> <experience>
    aliases: [ 'adde' ]
  enchant:
    description: Adds an enchantment to your current item
    usage: /<command> <enchantmentid> <level>
  toggleinvispickup:
    description: Toggle the picking up of items for invisble players
    usage: /<command>
    aliases: [ 'tip' ]