# This is a special feature of TCUtils, where a player_join and kick/quit even will be invisible.
# It will also be impossible for players that do not have the required permission to teleport to
# him and/or show up in /who
invisible-playerlist: [ 'notch' ]

extra:
# Set this to true if you want pigs to drop a saddle if you kill them when
# they have a saddle on them
# Warning: this can create infini-saddles when you have mount.paysaddle set to false
    recoverPigSaddle: false
# This features stops the ignite if you have god mode enabled in WorldGuard.
# doesn't work flawlessly though.
    stopGodIgnite: false
# Stops chunks unloading when there's a burning furnace inside of the chunk.
    stopChunkUnloadBurningFurnace: false
# Enables the Support for our ImprovedChat fork, to display your current chatmode in your chat bar
    CUI: false
# This enables support for our Bukkit tool durability per-world status mod.
# Needs a custom diff to work. Will send you the diff if you need it
    mod_InfDura: false
# This is mostly for the older Bukkit builds where exp orbs would lag your server
    stopExperienceOrbs: false


mount:
# Pay a saddle to mount something. When you set this to false, saddling pigs don't charge
# saddles either.
    paysaddle: true
# This config node lets you auto-tame wolves when a player mounts a wolf. They'll still need the correct
# permission node.
    autotame: false

spamcontrol:
    enable: true
    checkTime: 5
    muteTime: 5
    maxMessages: 5
    muteMessage: '{displayname} has been auto-muted for {mins} mins for spamming!'

PlayerHistory:
    enabled: true

Persistence:
    enabled: true
# This is an internally used method. You can use this to track users on IRC as well.
    useTweakBotSeen: false

ChatMode:
    LocalChat:
       enabled: true
       range: 200
    RegionChat:
       enabled: true # requires sk89q's WorldGuard plugin
    ZoneChat:
       enabled: true # requires Meaglins's Zones plugin
    WorldChat:
       enabled: true
    GroupChat:
       enabled: true

# Small note: The default CraftIRC doesn't send %prefix% and %suffix% that well.
# Therefor it's disabled by default. It sends the ยง values out to IRC.
# 2.2.3 Splits up admin & regular CraftIRC channels.
CraftIRC:
    enabled: false
    admin:
        enabled: false
        tag: 'mchatadmin'
# Support : %name%     -> Sendername
#           %message%  -> The sent message
#           %clearcolor%> ((char) 3) char
#           The other stuff will get parsed by CraftIRC itself.
        MessageFormat: '[A] <%sender%%clearcolors%> %message%'
    regular:
        enabled: false
        tag: 'mchat'
        MessageFormat: '<%name%> %message%'


# Pretty rudimentary spam control, should be self explanitory?
spamcontrol:
    enable: false
    checkTime: 10
    muteTime: 5
    maxMessages: 5
    muteMessage: '{displayname} has been auto-muted for {mins} mins for spamming!'


# This will enable a respawn hook, that will set your respawn point to the world
# you died in (and drop you from its nether if you were in one)
# Will also heal you to full HP if enabled
respawn:
    enableHook: false
    healOnRespawn: false

extrahelp:
    plugins: [TweakWarp, Homes, WorldEdit]
    hide: []

tamer:
   enabled: true
   toolid: 280 # Stick

worlds:
   enable: true
   enablenether: false
   netherfolder: 'nether'
   cancelportal: false
   extraworlds:
      newbieworld:
         environment: normal
         enabled: true
         pvp: true
         animals: true
         monsters: false
# This flag needs extra.mod_InfDura set to true, and a custom patch installed!
         durability: false
         addnether: false
         portalSearchRadius: 32
      mobs:
         environment: normal
         enabled: true
         pvp: true
         animals: true
      sky:
         environment: skylands
         enabled: true
         pvp: false
         animals: false
         monsters: false
