invisible-playerlist: []

PlayerHistory:
    enabled: true

Persistence:
    enabled: true
# This is an internally used method. You can use this to track users on IRC as well.
    useTweakBotSeen: false

ChatMode:
    LocalChat:
       enabled: true
       distance: 200
    RegionChat: true # requires sk89q's WorldGuard plugin
    ZoneChat: true   # requires Meaglins's Zones plugin
    WorldChat: true
    GroupChat: true

# Small note: The default CraftIRC doesn't send %prefix% and %suffix% that well.
# Therefor it's disabled by default. It sends the ยง values out to IRC.
# 2.2.3 Splits up admin & regular CraftIRC channels.
CraftIRC:
    enabled: false
    admin:
        enabled: false
        tag: 'mchatadmin'
# Support : %name%     -> Sendername
#           %message%  -> The sent message
#           The other stuff will get parsed by CraftIRC itself.
        MessageFormat: '[A] <%name%> %message%'
    regular:
        enabled: true
        tag: 'mchat'
        MessageFormat: '<%name%> %message%'

extrahelp:
    plugins: [TweakWarp, Homes, WorldEdit]
    hide: []

tamer:
   enabled: true
   toolid: 280 # Stick

worlds:
   enablenether: true
   netherfolder: 'nether'
   extraworlds:
      newbieworld:
         environment: normal
         enabled: true
         pvp: true
      mobs:
         environment: normal
         enabled: true
         pvp: true
      sky:
         environment: skylands
         enabled: true
         pvp: false
